---
title: "EDA Interativa sobre séries no IMDB"
subtitle: ''
author: "José Benardi de Souza Nunes"
output:
  html_document:
    df_print: paged
    toc: yes
    toc_float: yes
  html_notebook:
    toc: yes
    toc_float: yes
---

<br></br>

## Introdução

### Conjunto de dados utilizado

> Análise exploratória de dados do [IMDB](https://www.imdb.com/)  sobre seriados de TV e Streaming. Os dados originais e as variáveis vêm [deste repositorio](https://github.com/nazareno/imdb-series) . Lá consta a explicação de como os dados foram gerados e do significado de cada variável.

```{r setup, echo=FALSE, warning=FALSE, message=FALSE}
library(tidyverse)
library(here)
library(plotly)
theme_set(theme_bw())
```

```{r}
episodes <- read_csv(here("data/series_from_imdb.csv"), 
                    progress = FALSE,
                    col_types = cols(.default = col_double(), 
                                     series_name = col_character(), 
                                     episode = col_character(), 
                                     url = col_character(),
                                     season = col_character())) 
episodes %>% 
    glimpse()
```

```{r}
episodes <- left_join(episodes, sumario_simples,
                      by = c("series_name", "season")) %>% 
    group_by(series_name, season) %>%
    mutate(middle_eps = (season_ep > p20) &
               (season_ep < p80)) %>% 
    ungroup()
episodes
```


```{r}
 p <- episodes %>% 
          ggplot(aes(x = series_name,
                 y = user_rating,
                 color=series_name)) + 
        facet_wrap(~ season) + 
        geom_boxplot(position = position_dodge(width = 0.9)) +
        theme(axis.title.x=element_blank(),
              axis.text.x=element_blank(),
              axis.ticks.x=element_blank())

ggplotly(p)
```

```{r}
p <-  episodes %>% 
      ggplot(aes(x = series_name, y = user_rating, color=middle_eps)) + 
        geom_boxplot(alpha =0.3) +
        facet_wrap(~ season) +
        coord_flip()

ggplotly(p)
```
