---
title: "EDA LAB 1 - Checkpoint 3"
output:
  html_notebook:
    toc: yes
    toc_float: yes
  html_document:
    df_print: paged
    toc: yes
    toc_float: yes
---

## Conjunto de dados utilizado

Análise exploratória de dados do [IMDB](https://www.imdb.com/)  sobre seriados de TV e Streaming. Os dados originais e as variáveis vem [dneste repositorio](https://github.com/nazareno/imdb-series) . Lá tem a explicação de como os dados foram gerados e do significado de cada variável.

```{r setup, echo=FALSE, warning=FALSE, message=FALSE}
library(tidyverse)
library(here)
theme_set(theme_bw())
```


```{r}
episodes <- read_csv(here("data/series_from_imdb.csv"), 
                    progress = FALSE,
                    col_types = cols(.default = col_double(), 
                                     series_name = col_character(), 
                                     episode = col_character(), 
                                     url = col_character(),
                                     season = col_character())) 
episodes %>% 
    glimpse()
```

## Data Overview

```{r}
episodes %>%
    mutate(season = as.numeric(season)) %>%
    group_by(series_name) %>%
    summarise(n_seasons = max(season)) %>%
    ggplot(aes(n_seasons)) +
    geom_bar()
```


